{
 "title": "Matching Service Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Matching",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Requests Per Operation",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum (rate(service_requests{service_name=\"matching\"}[5m]))",
       "legendFormat": "requests"
      },
      {
       "expr": "sum (rate(service_errors{service_name=\"matching\"}[5m]))",
       "legendFormat": "errors"
      }
     ]
    },
    {
     "title": "Requests Per Operation",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (operation) (rate(service_requests{service_name=\"matching\"}[5m]))",
       "legendFormat": "{{operation}}"
      }
     ]
    },
    {
     "title": "Errors Break Down",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(service_errors_entity_not_found{service_name=\"matching\"}[5m]))",
       "legendFormat": "Entity Not Found"
      },
      {
       "expr": "sum(rate(service_errors_execution_already_started{service_name=\"matching\"}[5m]))",
       "legendFormat": "Execution Already Started"
      },
      {
       "expr": "sum(rate(service_errors_resource_exhausted{service_name=\"matching\"}[5m]))",
       "legendFormat": "Resource Exhausted"
      },
      {
       "expr": "sum by (__name__) (rate({__name__=~\"service_errors_.*\", service_name=\"matching\"}[5m]))",
       "legendFormat": "{{ $__name__ }}"
      }
     ]
    },
    {
     "title": "Latency",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "dtdurations" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(service_latency_bucket{service_name=\"matching\"}[5m])) by (operation, le))",
       "legendFormat": "{{operation}}"
      }
     ]
    }
   ]
  },
  { "title": "Tasks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Polls",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum(rate(poll_success[5m]))", "legendFormat": "Success" },
    { "expr": "sum(rate(poll_timeouts[5m]))", "legendFormat": "Timeouts" },
    {
     "expr": "sum(rate(poll_success_sync[5m]))",
     "legendFormat": "Sync Matches"
    }
   ]
  },
  {
   "title": "Throttled Requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate(sync_throttle_count[5m]))",
     "legendFormat": "Throttle"
    }
   ]
  },
  {
   "title": "Sync Match - Latencies",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(syncmatch_latency_bucket{service_name=~\"matching\"}[5m])) by (operation, le))",
     "legendFormat": "sync - {{operation}}"
    },
    {}
   ]
  },
  {
   "title": "Async Match - Latencies",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(asyncmatch_latency_bucket{service_name=~\"matching\"}[5m])) by (operation, le))",
     "legendFormat": "{{operation}}"
    },
    {}
   ]
  },
  {
   "title": "Forwarded Calls",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum(rate(forwarded[5m]))", "legendFormat": "forwarded_api_calls" }
   ]
  },
  {
   "title": "Local To Local Match",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (operation) (rate(local_to_local_matches[5m])) ",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "Local To Remote Match",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (operation) (rate(local_to_remote_matches[5m])) ",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "Remote To Local Match",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (operation) (rate(remote_to_local_matches[5m])) ",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "Remote To Remote Match",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (operation) (rate(remote_to_remote_matches[5m])) ",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  { "title": "Tasklist Manager", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "Lease Request Vs Failures",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum(rate(lease_requests[5m]))", "legendFormat": "requests" },
    { "expr": "sum(rate(lease_failures[5m]))", "legendFormat": "errors" }
   ]
  },
  {
   "title": "Expired Tasks",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum(rate(tasks_expired[5m]))", "legendFormat": "expired_tasks" }
   ]
  },
  {
   "title": "Throttle",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(sync_throttle_count[5m]))",
     "legendFormat": "sync_throttle"
    },
    {
     "expr": "sum(rate(buffer_throttle_count[5m]))",
     "legendFormat": "buffer_throttle"
    }
   ]
  },
  {
   "title": "Error Breakdown",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(condition_failed_errors[5m]))",
     "legendFormat": "condition_failed"
    }
   ]
  },
  { "title": "Persistence", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 } },
  {
   "title": "Request Vs Errors",
   "type": "graph",
   "gridPos": { "h": 10, "w": 10, "x": 0, "y": 59 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate(persistence_requests{service_name=\"matching\"}[5m]))",
     "legendFormat": "requests"
    },
    {
     "expr": "sum (rate(persistence_errors{service_name=\"matching\"}[5m]))",
     "legendFormat": "errors"
    }
   ]
  },
  {
   "title": "Requests Per Operation",
   "type": "graph",
   "gridPos": { "h": 10, "w": 7, "x": 10, "y": 59 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (operation) (rate(persistence_requests{service_name=\"matching\"}[5m]))",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "Errors Break Down",
   "type": "graph",
   "gridPos": { "h": 10, "w": 7, "x": 17, "y": 59 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "legendFormat": "{{operation}}" }
   ]
  },
  {
   "title": "Latency",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 69 },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(persistence_latency_bucket{service_name=\"matching\"}[5m])) by (operation, le))",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "History Client",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 79 },
   "collapsed": true,
   "panels": [
    {
     "title": "Requests Vs Errors",
     "type": "graph",
     "gridPos": { "h": 9, "w": 9, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(client_requests{service_name=\"matching\", service_role=\"history\"}[5m]))",
       "legendFormat": "requests"
      },
      {
       "expr": "sum(rate(client_errors{service_name=\"matching\", service_role=\"history\"}[5m]))",
       "legendFormat": "errors"
      }
     ]
    },
    {
     "title": "Requests Per Operation",
     "type": "graph",
     "gridPos": { "h": 9, "w": 7, "x": 9, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (operation) (rate(client_requests{service_name=\"matching\", service_role=\"history\"}[5m]))",
       "legendFormat": "{{operation}}"
      }
     ]
    },
    {
     "title": "Errors By Operation",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (operation) (rate(client_errors{service_name=\"matching\", service_role=\"history\"}[5m]))",
       "legendFormat": "{{operation}}"
      }
     ]
    },
    {
     "title": "Latency",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "dtdurations" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(client_latency_bucket{service_name=\"matching\", service_role=\"history\"}[5m])) by (operation, le))",
       "legendFormat": "{{operation}}"
      }
     ]
    }
   ]
  }
 ]
}