defaultRules:
  create: true
prometheus:
  ingress:
    enabled: true
    hosts:
      - "{{ prometheus_dns }}"
    paths:
      - /
  prometheusSpec:
    replicas: "{{ prometheus_replicas }}"
    podMonitorSelectorNilUsesHelmValues: false
    serviceMonitorSelectorNilUsesHelmValues: false
    ruleSelectorNilUsesHelmValues: false
    retention: "{{ prometheus_retention }}"
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: "{{ prometheus_storage_class }}"
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: "{{ prometheus_storage_size }}"